### ISSUE TITLE
Novo INSTALL.md

### ISSUE THREAD

**Issue by ppKrauss** [okfn-brasil/cuidando2#106]
Arquivo `.md` em substituição ao https://github.com/okfn-brasil/cuidando2/blob/master/doc/install.sh
pois não é seguro rodar cegamente um script, e seria deveras trabalhoso automatizar 100%. O melhor é o usuário ir fazendo copia/cola de trechos, consciente das explicações e comentários, até terminar.

A seguir algumas justificativas para modificações... Precisa?  Postar aqui mesmo?

**Comment by LuizArmesto** [comment]
Se não é seguro o usuário rodar um .sh também não é seguro ele rodar os .py do projeto :P

**Comment by ppKrauss** [comment]
A rigor a frase seria "rodar cegamente um script sh que não roda" ;-)

**Comment by ppKrauss** [comment]
@LuizArmesto , @andresmrm , e demais (quem mais?) hoje é meu prazo final para fazer testes e, principalmente, criar um INSTALL.md legível e confiável... Alguém pode dar uma ajuda objetiva?  Que tal marcarmos alguns horários de checklist por email?

**Comment by andresmrm** [comment]
Acho que o ideal é ter os dois: um INSTALL.md e um install.sh. Se não tivermos tempo de afinar o segundo, acho que ele deve permanecer mesmo assim, só deixamos um aviso.

**Comment by ppKrauss** [comment]
Oi gente, estamos iniciando o https://github.com/okfn-brasil/cuidando2-doc
onde centralizaremos a documentação, incluindo instalações e scripts ou "trechos de script" de instalação geral.
