### ISSUE TITLE
Verificar se o navegador tem localStorage e avisar se não tem

### ISSUE THREAD

**Issue by andresmrm** [okfn-brasil/cuidando2#18]
Se não tem, não é possível logar...

**Comment by ppKrauss** [comment]
... falta documentar melhor o que se pretende como localStorage, a principio basta uma cookie para session, storage do usuário seria no server... Algum esquema de certificação?

**Comment by andresmrm** [comment]
A parte de autenticação (Vira-Lata) usa tokens, e esses são armazenados no localStorage. Ou seja, não usamos cookies.

**Comment by andresmrm** [comment]
(coloquei uma descrição do protoloco de autenticação aqui: https://github.com/okfn-brasil/viralata#protocol )

**Comment by ppKrauss** [comment]
Sei que mais seguro é mais bacana, mas e o "arroz com feijão"? Já que o projeto por hora não vai ter votação, certificação do usuário eSIC (vai ser user OKBr afinal), etc. não bastaria a tradicional cookie e um protocolo simples?

**Comment by andresmrm** [comment]
Não... Uma vez que escolhemos micro serviços os tokens foram consequência...
Poderíamos não ter usado micro serviços? Sim. Mas foi por isso que eu apresentei a arquitetura para tod@s e tod@s concordaram que era uma boa.

**Comment by ppKrauss** [comment]
Ok, bola pra fente (!), pode-se usar essa função http://jsfiddle.net/6sm54/2/

Eu realmente não estava entendendo a issue...   As cookies serão obsoletas em poucos anos... Ah, otimo, agora temos um [link documentando o framework _viralata_](https://github.com/okfn-brasil/viralata) ;-)

---

... Se era "discutir conceito", escreveremos uma tese ;-)

## Papo de mesa de bar

Eu gosto de comparar arquiteturas Microservice com RISC, ou seja, a dicotomia de "Service vs Microserve" com "[SISC vs RISC](https://en.wikipedia.org/wiki/Reduced_instruction_set_computing#Comparison_to_other_architectures)"... Pois esse é o ponto central. O resto é modismo e frameworks. Não encontrei documentação sua criando restrição de framework, até aqui pareciam decisões mais conceituais. O conceito de Microservices nada tem de compromisso com HTML5 ou LocalStorage...

Exemplo: nada impede de armazenar tokens temporárias localmente em cookies... LocalStorage é um recurso novo do HTML5, se tem em mente um publico que 90% vai estar equipado com ao menos versão nova do DOM no browser, sem problemas (!). 

PS:  O Viralata está "aberto a palpites" ou podemos dar ele por encerrado?

## Cookie or not cookie

Alguns links que dizem usar,
- https://itservices.stanford.edu/service/kerberos/user_guide/how
- segundo [esse cara](https://books.google.com.br/books?id=k3RrCQAAQBAJ&pg=PA47&lpg=PA47&dq=Kerberos+token++cookie&source=bl&ots=vP6p7aUvcR&sig=03VrOJtlTAw_jOJAcd-YIUaEhDo&hl=pt-BR&sa=X&redir_esc=y#v=onepage&q=Kerberos%20token%20%20cookie&f=false) a Microsoft usava uma combinação de Kerberos com cookie-based token

Alguns que dizem não usar para autenticação/certificados (o mesmo argumento vale para LocalStorage!), mas nada dizem sobre as tokens temporárias, http://programmers.stackexchange.com/q/222503/84349

**Comment by andresmrm** [comment]
Sim, Peter, eu sei que dá para guardar um token no em um cookie. Mas o localStorage me pareceu a melhor escolha dado que já estavamos usando token, que a API teria facilidade para lidar com isso, que seria mais seguro, mais facil de manusear no cliente, etc etc etc.

Aqui tem uma estimativa de quantos % suportam localStorage:
http://caniuse.com/#feat=namevalue-storage

E Peter, essa issue era só para lembrar de mostrar um aviso para o usuário caso o navegador dele não suporte localStorage... Não para rediscutir a questão...

**Comment by ppKrauss** [comment]
Ah, ops... sorry (!)... Agora entendi aquele label vermelho de "obrigatório" ;-)

Continua de pé o pedido de _hangouts_ (!), para nos alinharmos sobre essa centena de issues e tarefas...  e antes de perdermos tempo escrevendo nas issues. 

PS:  não seria adequado já ir esboçando, mesmo que na WIki, o "manual do usuário"?
