### ISSUE TITLE
Trocar tamanhos de strings para potências de 2

### ISSUE THREAD

**Issue by andresmrm** [okfn-brasil/cuidando2#19]
Eu vi por aí que quando colocam um tamanho para uma coluna String no BD, costumam usar potência de 2 (64, 128, etc). Isso é importante? Ou pode ser 100, 200 etc?
Se for importante, temos que mudar isso em todos os repositórios.

**Comment by ppKrauss** [comment]
Se o BD  é o PostgreSQL, não é nada... No passado, bem passado as potencias de faziam sentido, hoje os tamanhos de campo, `varchar` principalmente, são arbitrários... sem traumas.

**Comment by andresmrm** [comment]
Imaginei que fosse algum "fantasma" do passado. =P
Vlw! =)
