### ISSUE TITLE
Ver se é problemático hospedar cada serviço em uma porta e não "domínio"

### ISSUE THREAD

**Issue by andresmrm** [okfn-brasil/cuidando2#27]
É ruim colocar microserviços em?

cuidando.org.br:5002
cuidando.org.br:5003
cuidando.org.br:5004

Ao invés de:

auth.cuidando.org.br
comments.cuidando.org.br
esic.cuidando.org.br

O segundo caso é mais elegante, mas parece que precisaria de um certificado mais caro.

**Comment by ppKrauss** [comment]
E porque não `ws.cuidando.org.br/auth`, `ws.cuidando.org.br/esic`, etc.?
Ver [exemplo](http://xmlfusion.org/demo/urn-microservice/) ([git](https://github.com/okfn-brasil/ISSN-L-Resolver)).

**Comment by andresmrm** [comment]
Essa era uma possibilidade que pensei também... Mas a última vez que tentei colocar algo no <domínio>/<algo> foi uma dor de cabeça tremenda. Mas poderíamos tentar.
Mas não poderia ter o "ws." na frente. Porque isso seria outro domínio e precisaríamos de outro certificado.

**Comment by alexandre** [comment]
Pode ser interessante considerar esse recurso:
http://flask.pocoo.org/docs/0.10/patterns/appdispatch/

[ ]'s

2015-08-17 10:56 GMT-03:00 Andrés Martano notifications@github.com:

> Essa era uma possibilidade que pensei também... Mas a última vez que
> tentei colocar algo no / foi uma dor de cabeça tremenda. Mas poderíamos
> tentar.
> Mas não poderia ter o "ws." na frente. Porque isso seria outro domínio e
> precisaríamos de outro certificado.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/okfn-brasil/cuidando2/issues/27#issuecomment-131825985
> .

## 

## 

## Twitter: @_AleSou || GitHub: alexandre || Reddit: ubbersith

[...]o sentido disso tudo é que não há sentido em tentar enlouquecer
para impedir-se de ficar louco...guarde sua sanidade para mais
tarde[...] - Douglas Adams

**Comment by andresmrm** [comment]
Ah, era disso que você tinha falado. =)
Mas será que faz sentido quando cada micro service é uma aplicação, e ainda quando estamos fazendo o deploy via mod_wsgi? (podemos mudar o segundo, o primeiro não)

**Comment by LuizArmesto** [comment]
+1 pra sugestão do ppKrauss

**Comment by ppKrauss** [comment]
Sobre a nomenclatura do `/`  na ausência de subdomínio, sugiro  `cuidando.org.br/ws/auth`, `cuidando.org.br/ws/esic`, etc. 

Quanto ao redirecionamento dos `/` (em endereços não-raiz), posso ajudar no que precisar nas [configurações Apache](http://httpd.apache.org/docs/current/mod/mod_rewrite.html) (ex. no `.htaccess` )... Já fiz isso em vários hostings.

PS: meu sonho de consumo para _microservices_ não é Apache, mas [NGINX](https://www.nginx.com/blog/realtime-applications-nginx/)  ;-)

---

## NOTAS

Foi dito "seria outro domínio"... Só para conferir jargão, eu costumo me referir a "ws.cuidando.org.br" e "xpto.cuidando.org.br" como _endereços de raiz_, ambos pertencem ao mesmo [domínio](https://en.wikipedia.org/wiki/Domain_name), mas o primiero com [subdomínio](https://en.wikipedia.org/wiki/Subdomain) "ws" e o segundo com subdomínio "xpto"... Neste jargão o dito correto é "seria outro _subdomínio_".

---

(notas perdidas/filosóficas, **ignorar se <i>off-topic</i>**)

Sobre pagar por um novo _certificado_, seria certificado "HTTPS", é isso? Uma vez ouvi falar que é política comercial do hosting.

Questão pessoal em termos de "neura por segurança": a necessidade de tráfego de dados públicos e impessoais em HTTPS, nunca vi debatida na comunidade OKBr... A comunidade Mozzila por exemplo não teve consenso em torno da [proposta do diretor](https://blog.mozilla.org/security/2015/04/30/deprecating-non-secure-http/). 

Itens de meditação que me surgiram: 1) os dados dos _webservices_ são todos públicos, não carecem de segurança, bastaria o login ser seguro;  2) as chaves de tokens poderiam correr em GET (ou não há essa alternativa?), portanto não seriam mesmo encriptadas; 3) as justificativas para ter tudo-tudo-tudo em HTTPS são duas, [RFC6797](https://tools.ietf.org/html/rfc6797) e [RFC7258](https://tools.ietf.org/html/rfc7258), ambas são ainda vistas como "opções voluntárias" e seu escopo de aplicação não é um imenso consenso.

Enfim, a sugestão é **tocar o projeto com HTTPS-full sem problemas (!)**, sugiro apenas que alguém, em nome do projeto, deixe um pedido na Lista sobre parecer da comunidade para futuros projetos: 
 Queremos aqui no Brasil o _"deprecating non-secure HTTP"_? Queremos criar custo no que não precisava ter custo?

**Comment by andresmrm** [comment]
Vou dar uma olhada no esquema `/ws/...` então.

Peter, no Diário Livre estamos usando NginX. =)
Eu achei bem mais fácil de configurar. Mas na máquina da OK-Br eu achei melhor usar o Apache que já estava lá...

Tem razão, subdomínio é o termo certo. =)

1) É que temos webservices que não são dados apenas de dados públicos. O próprio sistema de login é um webservice é precisa de HTTPS.
2) Não entendi. Até onde sei [GET é encriptado, não?](https://stackoverflow.com/questions/4143196/is-get-data-also-encrypted-in-https)

> sugiro apenas que alguém, em nome do projeto, deixe um pedido na Lista sobre parecer da comunidade para futuros projetos

Não sei, mas estou sentindo, que pelo menos por enquanto, é melhor não começarmos nenhuma discussão do tipo na lista não...

**Comment by ppKrauss** [comment]
Andres, nas questões técnicas acho que todos aqui estão alinhados, me parece que fechou a issue.

---

Respondendo o _off-topic_ ;-) 

1) sim, indiretamente isso que expressei: o login fica no HTTPS, mas não sabia que havia mais coisa "sigilosa" além disso... Todos esses "sigilosos" correriam no HTTPS: se como a autenticação forem desacoplados dos demais... Mas se há algo mais além da autenticação, o conceito de "desacoplado" fica vago, então é melhor mesmo uniformizar tudo sob HTTPS.

2) As URLs (e o HTTPS GET é uma URL comum) não são encriptadas. O que você faz é encriptar a token, ou seja, o valor do parâmetro passado por GET.

Lista: sim, concordo, daqui um tempo, quando a poeira da Lista abaixar e voltar a existir uma "comunidade vibrante" para discutir.

**Comment by andresmrm** [comment]
Blz, fechando a issue. Só não sei se entendi direito a sugestão do @alexandre .
Seria equivamente, mas fazer a configuração no nível WSGI?
http://flask.pocoo.org/docs/0.10/patterns/appdispatch/#combining-applications
Ou seja, ou configuramos no Apache/NginX ou em um arquivo Python para WSGI?
Será que tem diferença de performance/memória?
A vantagem que vejo da abordagem Apache/NginX é que os serviços poderiam ficar em diferentes máquinas, certo? Não que realmente venhamos a fazer isso...

**Comment by andresmrm** [comment]
1) Bom, o GA não vai ser encriptado, pois precisaríamos de mais um certificado para isso.
2) Ah, entendi, parâmetros passados via URL estaríam visíveis. Ok, os tokens são sempre enviados no corpo da requisição.

**Comment by LuizArmesto** [comment]
Pelo que entendi a necessidade de certificado é só mesmo para o sistema de autenticação e de identificação. Precisa de HTTPS para fazer a autenticação com o viralata e depois para fazer a identificação nos requests subsequentes que precisem de identificação, como por exemplo com o tagarela, para simples proteção do token e não por ser informação confidencial. Se o token de identificação for transmitido sem encriptação, então não precisaremos de certificado para nada, nem autenticação, pois a segurança já estará comprometida.

**Comment by andresmrm** [comment]
> Se o token de identificação for transmitido sem encriptação

Você quer dizer sem HTTPS, né? Sim, todo o problema é: se roubarem seu token podem se passar por você. Por isso ele tem que ser sempre enviado via HTTPS.
