### ISSUE TITLE
Possibilidade de baixar dados

### ISSUE THREAD

**Issue by andresmrm** [okfn-brasil/cuidando2#32]
Acho que isso precisa mexer no GA.

**Comment by ppKrauss** [comment]
Basta definir em SQL... e um _crontab_ produziria o _zip_ diariamente... Ver requisitos (baixar _onfly_ dados parciais?)...  O projeto/arquitetura está prevendo independência do GA, o usuário estaria fazendo requisição direta dos serviços GA.

**Comment by andresmrm** [comment]
É, acho que isso teria que ser feito do lado do GA. Ter um script em Python que gere o CSV diariamente. Possivelmente rodando com o crontab mesmo.

**Comment by andresmrm** [comment]
Parte do GA implementada. Falta colocar o botão no site.

**Comment by andresmrm** [comment]
Botei um link geral simples, por enquanto.
