### ISSUE TITLE
Otimizar site

### ISSUE THREAD

**Issue by andresmrm** [okfn-brasil/cuidando2#33]
Otimizar número de requisições, tempo de carga, tamanho dos dados etc.

**Comment by andresmrm** [comment]
Usar isso para colocar todas as images em um arquivo só:
https://webassets.readthedocs.org/en/latest/builtin_filters.html#spritemapper

**Comment by andresmrm** [comment]
http://brunch.io ?
http://chaplinjs.org/ ?
http://emberjs.com/ ?
http://browserify.org/ ?

**Comment by alexandre** [comment]
AngularJs?

[ ]'s

On Mon, Aug 24, 2015 at 9:24 PM, Andrés Martano notifications@github.com
wrote:

> http://brunch.io ?
> http://chaplinjs.org/ ?
> http://emberjs.com/ ?
> http://browserify.org/ ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/okfn-brasil/cuidando2/issues/33#issuecomment-134423229
> .

## 

## 

## Twitter: @_AleSou || GitHub: alexandre || Reddit: ubbersith

[...]o sentido disso tudo é que não há sentido em tentar enlouquecer
para impedir-se de ficar louco...guarde sua sanidade para mais
tarde[...] - Douglas Adams

**Comment by andresmrm** [comment]
https://html5boilerplate.com/ ?
http://knockoutjs.com/ ?
http://riotjs.com/ ?

**Comment by andresmrm** [comment]
Carregar Jquery de CDN e separar plugins do código principal, que talvez mude com frequência:
https://stackoverflow.com/questions/21099528/multiple-files-on-cdn-vs-one-file-locally

**Comment by alexandre** [comment]
Podemos testar o riotjs...parece bem leve e funcional (reactjs-like). O que
acha?

[ ]'s

On Tue, Aug 25, 2015 at 7:07 AM, Andrés Martano notifications@github.com
wrote:

> Carregar Jquery de CDN e separar plugins do código principal, que talvez
> mude com frequência:
> 
> https://stackoverflow.com/questions/14356402/which-jquery-version-to-reference-for-cdn
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/okfn-brasil/cuidando2/issues/33#issuecomment-134545541
> .

## 

## 

## Twitter: @_AleSou || GitHub: alexandre || Reddit: ubbersith

[...]o sentido disso tudo é que não há sentido em tentar enlouquecer
para impedir-se de ficar louco...guarde sua sanidade para mais
tarde[...] - Douglas Adams

**Comment by andresmrm** [comment]
Simpatizo com a cara da RiotJS.
E ClojureScript?

[2015-08-25 11:24] Alexandre:

**Comment by alexandre** [comment]
Andrés,

ClojureScript parece bem legal e deixaria um +1 nele também. No meu caso,
existiria uma curva para aprender Clojure ou JS e a versão alegre/bem
humorada ficaria no Clojure. =P

[ ]'s

On Tue, Aug 25, 2015 at 11:50 AM, Andrés Martano notifications@github.com
wrote:

> Simpatizo com a cara da RiotJS.
> E ClojureScript?
> 
> [2015-08-25 11:24] Alexandre:
> 
> > Podemos testar o riotjs...parece bem leve e funcional (reactjs-like). O
> > que
> > acha?
> > 
> > [ ]'s
> > 
> > On Tue, Aug 25, 2015 at 7:07 AM, Andrés Martano <
> > notifications@github.com>
> > wrote:
> > 
> > > Carregar Jquery de CDN e separar plugins do código principal, que
> > > talvez
> > > mude com frequência:
> > > 
> > > https://stackoverflow.com/questions/14356402/
> > > which-jquery-version-to-reference-for-cdn
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > > https://github.com/okfn-brasil/cuidando2/issues/33#issuecomment-134545541>
> > > .
> > 
> > ## 
> > 
> > ## 
> > 
> > ## Twitter: @_AleSou || GitHub: alexandre || Reddit: ubbersith
> > 
> > [...]o sentido disso tudo é que não há sentido em tentar enlouquecer
> > para impedir-se de ficar louco...guarde sua sanidade para mais
> > tarde[...] - Douglas Adams
> > 
> > —
> > Reply to this email directly or view it on GitHub.*
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/okfn-brasil/cuidando2/issues/33#issuecomment-134611114
> .

## 

## 

## Twitter: @_AleSou || GitHub: alexandre || Reddit: ubbersith

[...]o sentido disso tudo é que não há sentido em tentar enlouquecer
para impedir-se de ficar louco...guarde sua sanidade para mais
tarde[...] - Douglas Adams

**Comment by andresmrm** [comment]
Eu estava querendo aprender Lisp, Cloujure é tipo isso. =P
E eu também teria uma curva para aprender, logo não é algo para amanhã, mas
quem sabe mais para frente? =)

[2015-08-25 11:53] Alexandre:

**Comment by alexandre** [comment]
:+1: 
Seria bem legal e interessante. =]

Obs.: Galera do Clojure ficaria brava com esse "é tipo lisp"...Clojure é um dialeto lisp. </troll>
[ ]'s

**Comment by andresmrm** [comment]
hahaha, é que não entendo muito da parada mesmo. =P

[2015-08-25 12:01] Alexandre:

**Comment by andresmrm** [comment]
Dei uma testatada em ClojureScript, mas seriam mais 80Kb já compactados de tamanho. Sem contar a curva de aprendizagem... Vou dar uma avaliada na Riot.

**Comment by andresmrm** [comment]
Dei uma olhada na Riot, achei bonita e o tamanho me agrada bastante. Mas fiquei na dúvida se ela permite fazer, de forma elegante, o que precisamos... Mais especificamente elementos compartilhados por várias views e que devem ser apenas escondidos e não destruído. Queria consultar alguém sobre isso no IRC deles, mas todos os canais que achei estavam vazios...

Outra coisa que acho que vai ser importante é uma cache para os AJAX. Vou abrir uma issue para isso.

**Comment by alexandre** [comment]
Show. Eu gosto da ideia de experimentar o ClojureScript, mas considerando a
curva...

Seguindo essa ideia, o que você acha do PureScript?

Sobre o riot: atitude legal; buscar ajuda no irc deve funcionar (quando
houver alguém =P)

[ ]'s

2015-08-29 14:07 GMT-03:00 Andrés Martano notifications@github.com:

> Dei uma olhada na Riot, achei bonita e o tamanho me agrada bastante. Mas
> fiquei na dúvida se ela permite fazer, de forma elegante, o que
> precisamos... Mais especificamente elementos compartilhados por várias
> views e que devem ser apenas escondidos e não destruído. Queria consultar
> alguém sobre isso no IRC deles, mas todos os canais que achei estavam
> vazios...
> 
> Outra coisa que acho que vai ser importante é uma cache para os AJAX. Vou
> abrir uma issue para isso.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/okfn-brasil/cuidando2/issues/33#issuecomment-136009877
> .

## 

## 

## Twitter: @_AleSou || GitHub: alexandre || Reddit: ubbersith

[...]o sentido disso tudo é que não há sentido em tentar enlouquecer
para impedir-se de ficar louco...guarde sua sanidade para mais
tarde[...] - Douglas Adams

**Comment by andresmrm** [comment]
Opa, parecido com Haskell, legal! Mas teria que ver se realmente valeria a pena trocar o código que já estamos usando...
Esses dias trombei com [Elm](http://elm-lang.org/). Parece bem legal também. Mas está ainda em estágio muito experimental...

**Comment by LuizArmesto** [comment]
Que mistureira essa issue, começou com otimização de assets, passou por frameworks frontend e terminou com transpilers? :p

Meus 2 centavos...

Sobre otimizar os assets, é uma boa, mas os ícones do mapa é mais fácil deixa-los em arquivos próprios. Que eu me lembre o leaflet não trabalha com sprite direto, precisaria procurar ou até criar um plugin.
Sobre framework frontend, a escolha depende de quais são os requisitos do projeto e da familiaridade dos desenvolvedores, que influenciará na curva de aprendizagem.
Sobre linguagens "transpiladas", minha opinião é que só aumenta a barreira de entrada para novos colaboradores. Se for alguma não muito utilizada corre-se o risco de se deparar com bugs no transpiler e de ser abandonada em algum momento.

**Comment by andresmrm** [comment]
Hahaha, tem razão, virou uma mistureira mesmo isso aqui. =P

Boa, deixar os ícones do mapa em separado.

Então, eu vi os frameworks, e não achei que nenhum agregaria muito, pelo menos não no estágio atual do projeto e considerando que seriam mais KBs. Mas eu também não entendo muito deles...
Um dos meus medos é pegar um framework e depois acabar fazendo umas gambs nele para chegar onde precisamos...

Sobre as transpiladas, eu gostaria de mexer com algumas, mas acho que isso podemos tocar, talvez depois, como "projeto paralelo", afinal, as APIs deixam qualquer cliente se comunicar com o sistema.

**Comment by andresmrm** [comment]
Dei uma olhada melhor na Riot, acho que pode ajudar sim. Estou pensando em começar a reestruturar a interface com ela.
Sobre as linguagens "transpiladas", estava pensando em pegar a ES6 via [Babel](https://babeljs.io/). Já que ganha algumas gracinhas sem sair do JS.

**Comment by alexandre** [comment]
@andresmrm parece uma boa. =]

**Comment by andresmrm** [comment]
Estou "rascunhando" aqui... =P

[2015-09-04 14:40] Alexandre:

**Comment by alexandre** [comment]
Legal. No backend precisamos considerar algumas "reestruturações" depois dos entregáveis.

Eu acho que já dá para fechar essa issue, não? =]

**Comment by andresmrm** [comment]
Blz. Uma parte que ficou pendende levei para cá:
https://github.com/okfn-brasil/cuidando2/issues/96
