### ISSUE TITLE
Automatizar atualização dos dados de execução

### ISSUE THREAD

**Issue by andresmrm** [okfn-brasil/cuidando2#35]

**Comment by ppKrauss** [comment]
Talvez decisão e desenvolvimento anteriores sejam com relativos à "intervenção humana":
- o projeto (Gastos ou Cuidando) vai prever possibilidade de correção manual?? Sabemos que muitos dados são "bichados" (~10% ou ~1%?), comprometendo a confiabilidade e usabilidade do projeto.
- a arquitetura (armazenamento diferenciado) e o protocolo de atualização, precisariam prever a opção manual.
- os "dados de execução" possuem ou não vinculo relevante com os "dados do Diário Livre"?

**Comment by andresmrm** [comment]
Eu diria que não...
O sentido dessa issue é colocar para rodar todo dia o script que extrai os dados e insere no BD do GA.

**Comment by andresmrm** [comment]
https://github.com/okfn-brasil/gastos_abertos/issues/186
