### ISSUE TITLE
Usar TopoJSON no lugar do GeoJSON?

### ISSUE THREAD

**Issue by andresmrm** [okfn-brasil/cuidando2#52]
Parece menor, mas não sei se vale a pena.
http://blog.webkid.io/maps-with-leaflet-and-topojson

**Comment by ppKrauss** [comment]
GeoJSON.

Justificativa: _"TopoJSON is an extension of GeoJSON that encodes topology"_ ([Wikipedia](https://en.wikipedia.org/wiki/GeoJSON#TopoJSON)); e no Cuidando2 não há representação topológica, só geométrica.

**Comment by andresmrm** [comment]
Sim, mas pelo que vi o TopoJSON é quase sempre menor do que o GeoJSON. Logo seriam menos bytes para transferir para os usuários.

**Comment by andresmrm** [comment]
Só para deixar mais claro, acho que poderia fazer sentido usar TopoJSON para o arquivo de subprefeituras:
https://github.com/okfn-brasil/cuidando2/tree/master/static/geojson

Mas isso realmente não está muito relacionando com o GA...

**Comment by ppKrauss** [comment]
Tudo é função e contexto: a função JSON da comunicação no Cuidando2, pelo que entendi, é efetivamente  comunicar geometrias... O contexto é PostGIS, IBGE, Sampa, etc. A informação topológica sem respectiva geometria, claro, será menor, mas há perda de informação. Por exemplo: não preciso da geometria dos polígonos de SP e MG para dizer que "SP é vizinho de MG".

**Comment by LuizArmesto** [comment]
Lembra de um email que mandei há um tempo sobre usar geojson compactado com gzip antes de tentar alternativas mirabolantes com o formato dos dados para diminuir o tamanho das requisições? Continuo com a mesma opinião, acho que não vale abrir mão das vantagens que o geojson tem (suporte já pronto tanto no backend quanto no frontend) para uma diminuição de footprint que nem foi avaliada para valer.

**Comment by vatsu** [comment]
+1 pra ativar gzip pra json no webserver.

**Comment by andresmrm** [comment]
Haha, tem razão, Luiz. Era mais curiosidade mesmo.
Pelo que vi, mesmo depois de compactado, o TopoJson consegue reduzir o arquivo
de subprefeituras pela metade em comparação com o GeoJson. E precisaria de
mais umas 10 linhas de código para fazer o Leaflet suportar esse formato.
Mas também não não sei se vale o esforço...

[2015-08-28 12:20] Luiz Armesto:

**Comment by andresmrm** [comment]
Opa, isso já tá! ;)

[2015-08-28 12:30] Gustavo Sales:

**Comment by vatsu** [comment]
Massa :D

2015-08-28 12:34 GMT-03:00 Andrés Martano notifications@github.com:

**Comment by LuizArmesto** [comment]
A minha avaliação é a seguinte: 

O geojson das subprefeituras compactado pesa 83K
O topojson + topojson.min.js compactados pesam juntos 50K
O primeiro carregamento completo do site na versão que está no ar (http://cuidando.org.br:5001/) pesa 688K

Você economizaria 33K de transferência (5% do total), mas em contrapartida teria que converter de volta para geojson no cliente para poder exibir no mapa. Teria uma pequena economia na transferencia, mas um aumento na complexidade do formato dos dados e no processamento.

;)

**Comment by andresmrm** [comment]
Vlw! Então por enquanto deixamos isso de lado. Se precisarmos passar muitos GeoJsons mais para frente (o que acho difícil) reavaliamos.

**Comment by ppKrauss** [comment]
Só resumindo o que eu disse meio enrolado: <b>NÃO USEM _TopoJSON_</b> nem no futuro, não faz sentido!! 

;-)

PS: vocês não estão representando **topologia** (é GEOMETRIA), a representação só coincide/funciona por serem apenas pontos, mas no futuro espera-se mais que pontos.
