### ISSUE TITLE
Decidir entre coletar as respostas via e-mail ou interface do site

### ISSUE THREAD

**Issue by andresmrm** [okfn-brasil/cuidando2#6]
É provável que a interface do site pagine os pedidos na lista deles (ex.: mostra 20 pedidos por vez). Essa seria mais uma dificuldade se fossemos coletá-los via interface do site.
Se for coletar da interface, aparentemente, quando um pedido é marcado como "finalizado" é ele não precisa mais ser acompanhado (não receberá mais respostas, e não é mais possível recorrer).

**Comment by andresmrm** [comment]
Submeti mais 6 pedidos para ver como retornam as respostas...

**Comment by andresmrm** [comment]
Aparentemente, mesmo quando são enviados e-mails, eles são menos completos do que pela interface do site. Logo, se tivesse que escolher uma, acho que iria pela do site.

Não se pode saber se um pedido teve ou não atualização vendo se a "Situação" está em "Em tramitação", pois pode acontecer dele ter um evento interno e continuar em tramitação. Logo teria que extrair todos os pedidos que não estão como "Finalizado" todos os dias...

**Comment by andresmrm** [comment]
Vamos usar o site então? @alexandre 
Fechando issue...

**Comment by alexandre** [comment]
:+1:
