### ISSUE TITLE
Dar uma analisada se há um jeito mais fácil de interagir com o eSIC do que via Selenium.

### ISSUE THREAD

**Issue by andresmrm** [okfn-brasil/cuidando2#7]

**Comment by andresmrm** [comment]
Pelo que vi, eles enviam o ID do elemento da interface que foi clicado no POST. Estou achando mais fácil usar o Selenium mesmo...
Chegou a dar uma olhada, @alexandre ?

**Comment by alexandre** [comment]
Andrés,

Ainda não, mas te dou uma resposta nesse final de semana (vou trabalhar
nessa issue). Ok?

[ ]'s

2015-08-21 9:01 GMT-03:00 Andrés Martano notifications@github.com:

> Pelo que vi, eles enviam o ID do elemento da interface que foi clicado no
> POST. Estou achando mais fácil usar o Selenium mesmo...
> Chegou a dar uma olhada, @alexandre https://github.com/alexandre ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/okfn-brasil/cuidando2/issues/7#issuecomment-133391224
> .

## 

## 

## Twitter: @_AleSou || GitHub: alexandre || Reddit: ubbersith

[...]o sentido disso tudo é que não há sentido em tentar enlouquecer
para impedir-se de ficar louco...guarde sua sanidade para mais
tarde[...] - Douglas Adams

**Comment by andresmrm** [comment]
Ok! Também não precisa perder muito tempo com ela não. =P
É mais para ter uma segunda opinião.

[2015-08-21 11:07] Alexandre:

**Comment by andresmrm** [comment]
Selenium mesmo? @alexandre 
Fechando...

**Comment by alexandre** [comment]
Selenium :+1:

On Sat, Aug 22, 2015 at 12:36 PM, Andrés Martano notifications@github.com
wrote:

> Closed #7 https://github.com/okfn-brasil/cuidando2/issues/7.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/okfn-brasil/cuidando2/issues/7#event-389538154.

## 

## 

## Twitter: @_AleSou || GitHub: alexandre || Reddit: ubbersith

[...]o sentido disso tudo é que não há sentido em tentar enlouquecer
para impedir-se de ficar louco...guarde sua sanidade para mais
tarde[...] - Douglas Adams
