### ISSUE TITLE
Uma nova pagina é aberta ao clicar em um ponto.

### ISSUE THREAD

**Issue by alexandre** [okfn-brasil/cuidando2#81]
Eu tentei clicar em um ponto, mas ao invés de apenas renderizar os dados, a aplicação se comporta como se eu tivesse clicado na opção "Baixar Dados".

Alguns detalhes:
- Teste com o Firefox e o Chromium;
- Todas as aplicações relacionadas no ambiente local.
- Todos os clicks redirecionam para: http://site.gastosabertos.org/

cc/ @andresmrm 

[ ]'s

**Comment by andresmrm** [comment]
Tinha esquecido de fechar a tag 'a'. =P

[2015-08-23 00:15] Alexandre:
