### ISSUE TITLE
Erro ao adicionar um comentário

### ISSUE THREAD

**Issue by alexandre** [okfn-brasil/cuidando2#82]
A mensagem de erro:

```
"Error: User not found!. You have requested this URI [/renew_micro_token] but did you mean /renew_micro_token ?"
```

A unica aplicação que eu não estou rodando na minha máquina é o Gastos Abertos. Pode ser um problema?
[ ]'s

**Comment by andresmrm** [comment]
Não era para ser não...
Essa msg apareceu em um alert?

[2015-08-23 11:03] Alexandre:

**Comment by alexandre** [comment]
@andresmrm sim.
