### ISSUE TITLE
Reduzir tamanho do JS

### ISSUE THREAD

**Issue by andresmrm** [okfn-brasil/cuidando2#87]
Jquery.min: 82Kb (difícil se livrar dele... talvez carregar de CDN e ter sorte de estar na cache?)
Leaflet.min : 122Kb (mesma coisa do de cima)
HighCharts.min: 160Kb (parece um bom candidato para trocar)
Datatables: 78Kb (usar outro módulo?)
Bootstrap.min: 36Kb (talvez dê para pegar apenas o necessário)

**Comment by andresmrm** [comment]
Talvez trocar HC por http://www.flotcharts.org/ ? Depende do que vamos precisar...

**Comment by LuizArmesto** [comment]
Jquery e bootstrap é bem provavel que usando CDN o cliente já tenha no cache, mas tem que avaliar se vale a pena mesmo.

Na versão que está atualmente no ar, com concatenação e gzip ativado, o arquivo javascript está pesando 191KB

**Comment by andresmrm** [comment]
Eu estava tendendo ao CDN, pelo menos para o Jquery. Acho que uma requisição a mais não seria problema nesse caso, não? Mas teria que ver mesmo quando dá a soma final, já que não estarão compactados no mesmo arquivo.

Acho que não vamos aumentar muito mais do que 200Kb (talvez até uns 250). Você acha que é razoável, Luiz? É que eu estava pensando, sei lá, em um 3G. Quanto é? 25Kb/s? Só o JS já levaria uns 10s? Mas sinto que não tem muito como melhorar isso considerando que temos mapa, gráfico e tabela. A não ser que cortemos parte das libs fora ou façamos na mão...

**Comment by andresmrm** [comment]
Novo código em RiotJS só usa Leaflet.

**Comment by alexandre** [comment]
esse RioJS trouxe boas novidades...

Boa, Andrés.

[ ]'s

2015-09-17 11:20 GMT-03:00 Andrés Martano notifications@github.com:

> Novo código em RiotJS só usa Leaflet.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/okfn-brasil/cuidando2/issues/87#issuecomment-141101932
> .

## 

## 

## Twitter: @0x41e || GitHub: alexandre || Reddit: ubbersith

[...]o sentido disso tudo é que não há sentido em tentar enlouquecer
para impedir-se de ficar louco...guarde sua sanidade para mais
tarde[...] - Douglas Adams

**Comment by andresmrm** [comment]
Você que me incentivou a tentar. =)
Acho que a maioria das coisas ficou bem mais organizadas mesmo.
