### ISSUE TITLE
Cache para a AJAX

### ISSUE THREAD

**Issue by andresmrm** [okfn-brasil/cuidando2#93]
Seria bom "cachear" as requisições AJAX para não ficar repetindo-as quando muda de página e volta.
Estou tendendo a usar uma cache por sessão. Mas alguns dados talvez precisariam ser atualizados mesmo dentro de uma mesma sessão... Comentários? Últimas atividades?

**Comment by LuizArmesto** [comment]
Se as requisições ajax são feitas com jquery, dá para implementar um cache usando o $.ajaxTransport

"There are only two hard things in Computer Science: cache invalidation and naming things."
-- Phil Karlton

**Comment by andresmrm** [comment]
Haha, boa essa sobre a cache, @LuizArmesto  =P

Na nova arquitetura, usando RiotJS à la Flux com RiotControl, as stores já estão funcionando como cache. Dai fica o problema de invalidar essa cache, pois sem recarregar a página ele não fai pegar novos comentários/atualizações. Vou abrir outra issue sobre isso.

**Comment by andresmrm** [comment]
Esqueci de deixar claro, as stores funcionam como cache durante a sessão. Se o navegador for reaberto ou a página recarregada, a cache é perdida (são variáveis comuns). Exceto os tokens de autenticação, que ficam na localStorage e persistem.
